### PR TITLE
Fixes for unicode in changesets. Added testcase for unicode

### PR DESCRIPTION
**Pull request by MichaelVL**
Proposed fix for issue #57

### CODE REVIEW

**Comment by austinhartzheim** [comment]
@metaodi It looks like the test is failing due to legacy code and a specific version of flake8. Based on a quick check, it looks like we can remove the debug() function - I don't see it being used anywhere.

**Comment by MichaelVL** [comment]
But that is a separate issue - something we should keep in another pull-request, right?

The unittests pass nicely.

**Comment by MichaelVL** [comment]
How do we proceed with this?

FYI - there is a useful feature enabled by the refactoring to use requests, which is why I like to see the stable osmapi move forward to the requests-based implementation. This useful feature is that one can specify a port in the api url, e.g. 'https://api.openstreetmap.org:8000'. This does not work with the current 'stable' version.

**Comment by metaodi** [comment]
@MichaelVL Sorry for the long wait! I finally found the time to look into this, fix the build and merge your PR. The new release is on it's way.

**Pull request merged**
